# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ba99bc4d78e6b72152f6a4099807b5106e185d5edadcce2cb4c7347d32a711e46315cb01f19338ca1f69dc92908b0fed5d1711e632bd121489b0c3ddc8a16dd5

test:
  secret_key_base: 01ce9c801a9a4c7c648a995b2c785fe3b1806e52e70c36c5f169887e82131450236c370ceba03f7a5bd91766f5f4c015a07cfd3b64c1fae2988acec47d0c49dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
